### ISSUE TITLE
Update settings section with recipe calculator options.

### ISSUE THREAD

**Issue by SimonNguyen** [SimonNguyen/ProductionChain#7]
Select an item based on a search over the list of items in the recipes.
Number of machines must be whole numbers and blocks per minute do not need to be whole numbers.

These values should be passed up to the DashboardPage component.

**Comment by SimonNguyen** [comment]
The list of items can be retrieved by passing a property to the `InformationSection` with the results from the `GetLabels(recipes)` function.

**Comment by Zelgoth** [comment]
Related change: Add 3 new columns 
- new column for calculated target inputs
- new column for calculated target outputs
- new column for calculated target machines
